Listens to MQTT topic /activeProgram to start programs for compatible devices
hcpy2-0/hcpy pull request #22
Opened 2024-03-19 21:00 UTC by Meatballs1

Resolves: https://github.com/hcpy2-0/hcpy/issues/7

This should allow the vast majority of home automation use cases to be performed.

2024-03-19 21:16 UTC, Meatballs1 commented
It would be good if people can test in the field to see if it works for them. I can trigger my devices using the MQTT configuration in HA for example:

![image](https://github.com/hcpy2-0/hcpy/assets/1854557/395725a1-0b8d-4555-b9ca-7b8abcd7af0f)

2024-03-19 22:47 UTC, pmagyar requested changes

2024-03-19 22:47 UTC, pmagyar commented on HCDevice.py
> +        if isinstance(data["program"], str):
in my opinion you can make the if shorter if you catch the ValueError:
`
>>> bla="blub"
>>> if isinstance(bla, str):
...   print("True")
...
True
>>> if isinstance(int(bla), int):
...   print("is int")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'blub'
>>> bla="1111"
>>> if isinstance(int(bla), int):
...   print("is int")
...
is int
>>>`

Can you check this?

2024-03-20 13:09 UTC, pmagyar approved these changes
Great work!

2024-03-20 13:09 UTC, merged